web/router.ex
defmodule Meshi.Router do
  use Meshi.Web, :router
  require Ueberauth
  require Logger

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.Pipeline, module: Meshi.Guardian, error_handler: Meshi.AuthErrorHandler
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug :fetch_session
  end

  pipeline :slack do
    plug :accepts, ["json"]
    plug Plug.Parsers, parsers: [:urlencoded]
    plug :token_match
  end

  scope "/api", Meshi do
    pipe_through :api # Use the default api stack

    resources "/restaurants", RestaurantController, only: [:index, :show, :create, :update, :delete]
  end

  scope "/", Meshi do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/slack/webhook", Meshi do
    pipe_through :slack # Use the slack stack

    # Slack will periodically send get requests
    # to make sure the bot is still alive.
    get "/", SlackController, :ping

    post "/", SlackController, :query
  end

  scope "/auth", Meshi do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  defp token_match(conn, _params) do
    slack_token = Application.get_env(:meshi, :slack_token)
    case conn.params do
      %{"token" => token} when token == slack_token -> conn
      _ ->
        conn |> put_status(:bad_request) |> send_resp(404, "bad request") |> halt
    end
  end
  # Other scopes may use custom stacks.
  # scope "/api", Meshi do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Meshi.LayoutView do
  use Meshi.Web, :view

  def socket_url(current_user) do
     "#{socket_url()}?token=#{token(current_user)}"
  end

  def token(current_user) do
    {ok, jwt, _} = Guardian.encode_and_sign(Meshi.Guardian, current_user)
    jwt
  end

  def socket_url, do: System.get_env("WEBSOCKET_URL") || "ws://localhost:4000/socket/websocket"
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name="guardian_token" content="<%= Guardian.Plug.current_token(@conn) %>">
    <% end %>

    <title>Meshi!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <div class="nav pull-right" style="padding-top:20px;">
              <%= if @current_user do %>
                <img src="<%= @current_user.avatar %>" class="img-circle" style="padding-right: 5px; height: 30px;"></img>
                <%= button "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger btn-sm" %>
              <% else %>
                  <a class="btn btn-primary btn-sm" href="/auth/google">
                    <i class="fa fa-google"></i>
                    Sign in with Google
                  </a>
              <% end %>
          </div>
        </nav>
        <span class="logo"></span>
        <span style="font-size: 40px; vertical-align: top;">Meshi ?</span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= if @current_user do %>
          <%= render @view_module, @view_template, assigns %>
        <% else %>
          <div style="width: 100%; height: 400px; text-align: center; font-size: 60px;">Please sign-in</div>
        <% end %>
      </main>

    </div> <!-- /container -->
    <div>Logo made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKj8Np2MfBq4GA7sxmyy3gQSOhKhhJPRk&libraries=places"></script>
    <%= if @current_user do %>
      <script>
        window.socketUrl = '<%= Meshi.LayoutView.socket_url(@current_user) %>';
        window.token = '<%= Meshi.LayoutView.token(@current_user) %>'
      </script>
      <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <% end %>
  </body>
</html>